//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string BookID { get; set; }
        public string BookName { get; set; }
        public int CategoryID { get; set; }
        public int PublishID { get; set; }
        public string ISBN { get; set; }
        public double BookCost { get; set; }
        public double BookPrice { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
