//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Inv_id { get; set; }
        public string Inv_no { get; set; }
        public Nullable<System.DateTime> Inv_date { get; set; }
        public Nullable<decimal> Inv_amont { get; set; }
    }
}
