//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public int id { get; set; }
        public Nullable<double> amt_float { get; set; }
        public Nullable<decimal> amt_number { get; set; }
        public Nullable<decimal> amt_decimal { get; set; }
        public Nullable<decimal> amt_money { get; set; }
    }
}
